/**
 * @file transition_dag.hpp
 * @brief Transition DAG used by horizon and successor encoders.
 *
 * The DAG stores states, edges, actions, and optional candidate ids. It does
 * not know anything about relation names, batching, or graph export.
 */
#pragma once

#include <concepts>
#include <cstdint>
#include <loki/details/utils/hash.hpp>
#include <mimir/formalism/ground_action.hpp>
#include <mimir/search/state.hpp>
#include <optional>
#include <ranges>
#include <type_traits>
#include <vector>

#include "mifrost/core/common_types.hpp"
#include "mifrost/core/encoders/common/goal_inputs.hpp"
#include "mifrost/core/utils/type_traits.hpp"

// Delegate to mimir's existing loki::Hash<State> specialization
namespace std {
template <>
struct hash< mimir::search::State > {
   std::size_t operator()(const mimir::search::State& state) const noexcept
   {
      return loki::Hash< mimir::search::State >{}(state);
   }
};
}  // namespace std

namespace mifrost {

/**
 * @brief Directed Acyclic Graph (DAG) of state transitions for lookahead encoding.
 *
 * Represents a tree/DAG of successor states reachable from a root state,
 * typically generated by IW search or other lookahead algorithms.
 *
 * Each node has:
 * - state: The state at this node (lightweight handle)
 * - index: Insertion order (stable for iteration)
 * - depth: Distance from root
 * - action: Optional action that led to this state
 *
 * Edges represent parent→child transitions in the search tree.
 *
 * Invariants:
 *  - node indices are stable insertion-order ids
 *  - `root_index()` is always `0`
 *  - depths are recomputed from edges, not trusted from insertion order
 */
class TransitionDAG {
  public:
   /// One bulk transition import record.
   struct TransitionRecord {
      mimir::search::State parent;
      mimir::search::State child;
      std::optional< mimir::formalism::GroundAction > action;
      std::optional< int64_t > candidate_id;
      std::optional< std::vector< LiteralVariant > > delta_literals;
   };

   /// One transition DAG node.
   struct Node {
      /// State represented by this node.
      mimir::search::State state;
      /// Stable insertion-order index.
      int64_t index;
      /// Depth from root.
      int depth;
      /// Optional incoming action from parent to this node.
      std::optional< mimir::formalism::GroundAction > action;
      /// Optional caller-provided candidate identity for this node.
      std::optional< int64_t > candidate_id;
      /// Optional caller-provided transition delta literals for this node.
      std::optional< std::vector< LiteralVariant > > delta_literals;
   };

   /**
    * @brief Construct a new TransitionDAG with the given root state.
    */
   explicit TransitionDAG(mimir::search::State root);

   /**
    * @brief Register a transition from parent to child.
    *
    * If the child state doesn't exist yet, it will be added.
    *
    * @param parent Parent state
    * @param child Child state
    * @param action Optional action that led from parent to child
    * @return Pair of (parent_idx, child_idx)
    */
   std::pair< int, int > register_transition(
      const mimir::search::State& parent,
      const mimir::search::State& child,
      std::optional< mimir::formalism::GroundAction > action = std::nullopt,
      std::optional< int64_t > candidate_id = std::nullopt,
      std::optional< std::vector< LiteralVariant > > delta_literals = std::nullopt
   );

   /**
    * @brief Register many transitions and recompute depths once.
    *
    * This accepts any input range of transition-like records exposing
    * ``parent``, ``child``, and ``action`` members.
    */
   template < std::ranges::input_range R >
      requires requires(detail::raw_t< std::ranges::range_reference_t< R > > rec) {
         { rec.parent } -> std::convertible_to< mimir::search::State >;
         { rec.child } -> std::convertible_to< mimir::search::State >;
         { rec.action } -> std::convertible_to< std::optional< mimir::formalism::GroundAction > >;
      }
   void register_transitions(R&& transitions)
   {
      bool has_records = false;
      for(auto&& rec : transitions) {
         has_records = true;
         const auto candidate_id = [&]() -> std::optional< int64_t > {
            if constexpr(requires { rec.candidate_id; }) {
               using candidate_ref_t = detail::raw_t< decltype(rec.candidate_id) >;
               if constexpr(std::is_convertible_v< candidate_ref_t, std::optional< int64_t > >) {
                  return static_cast< std::optional< int64_t > >(rec.candidate_id);
               } else if constexpr(std::is_convertible_v< candidate_ref_t, int64_t >) {
                  return std::optional< int64_t >{static_cast< int64_t >(rec.candidate_id)};
               } else {
                  static_assert(
                     std::is_convertible_v< candidate_ref_t, std::optional< int64_t > >
                        or std::is_convertible_v< candidate_ref_t, int64_t >,
                     "candidate_id must be convertible to optional<int64_t> or int64_t"
                  );
               }
            }
            return std::nullopt;
         }();
         const auto delta_literals = [&]() -> std::optional< std::vector< LiteralVariant > > {
            if constexpr(requires { rec.delta_literals; }) {
               using delta_ref_t = detail::raw_t< decltype(rec.delta_literals) >;
               if constexpr(std::is_convertible_v<
                               delta_ref_t,
                               std::optional< std::vector< LiteralVariant > > >) {
                  return static_cast< std::optional< std::vector< LiteralVariant > > >(
                     rec.delta_literals
                  );
               } else if constexpr(std::is_convertible_v<
                                      delta_ref_t,
                                      std::vector< LiteralVariant > >) {
                  return std::optional< std::vector< LiteralVariant > >{
                     static_cast< std::vector< LiteralVariant > >(rec.delta_literals)
                  };
               } else {
                  static_assert(
                     std::is_convertible_v<
                        delta_ref_t,
                        std::optional< std::vector< LiteralVariant > > >
                        or std::is_convertible_v< delta_ref_t, std::vector< LiteralVariant > >,
                     "delta_literals must be convertible to optional<vector<LiteralVariant>> "
                     "or vector<LiteralVariant>"
                  );
               }
            }
            return std::nullopt;
         }();
         register_transition_impl(
            rec.parent, rec.child, rec.action, candidate_id, delta_literals, false, false
         );
      }
      if(has_records) {
         finalize_depths();
      }
   }

   /**
    * @brief Get the index of a state in the DAG.
    * @throws std::out_of_range if state not in DAG
    */
   int index(const mimir::search::State& state) const;

   /**
    * @brief Get the depth of a node by index.
    */
   int depth(int idx) const;

   /**
    * @brief Get the action that led to a node by index.
    */
   std::optional< mimir::formalism::GroundAction > action(int idx) const;

   /**
    * @brief Get the state at a given index.
    */
   mimir::search::State state(int idx) const;

   /**
    * @brief Get children indices of a node.
    */
   const std::vector< int >* children(int parent_idx) const;

   /**
    * @brief Get all nodes in insertion order.
    */
   const std::vector< Node >& nodes() const { return nodes_ordered_; }

   /**
    * @brief Get all successor nodes (excluding root).
    */
   std::vector< Node > successors() const;

   /**
    * @brief Get all transitions as (parent_idx, child_idx) pairs.
    */
   std::vector< std::pair< int, int > > transitions() const;

   /**
    * @brief Get the root state.
    */
   mimir::search::State root() const { return root_; }

   /**
    * @brief Get the root index (always 0).
    */
   int root_index() const { return 0; }

   /**
    * @brief Check if a state exists in the DAG.
    */
   bool contains(const mimir::search::State& state) const;

  private:
   int get_or_add_node(
      const mimir::search::State& state,
      const std::optional< mimir::formalism::GroundAction >& action_for_new_node,
      const std::optional< int64_t >& candidate_id_for_new_node,
      const std::optional< std::vector< LiteralVariant > >& delta_literals_for_new_node
   );

   void set_or_validate_candidate_id(int node_idx, const std::optional< int64_t >& candidate_id);
   void set_or_validate_delta_literals(
      int node_idx,
      const std::optional< std::vector< LiteralVariant > >& delta_literals
   );

   std::pair< int, int > register_transition_impl(
      const mimir::search::State& parent,
      const mimir::search::State& child,
      const std::optional< mimir::formalism::GroundAction >& action,
      const std::optional< int64_t >& candidate_id,
      const std::optional< std::vector< LiteralVariant > >& delta_literals,
      bool recompute_depths,
      bool require_parent_exists
   );

   /// Recompute depth labels from current adjacency.
   void finalize_depths();

   mimir::search::State root_;
   int next_index_ = 0;

   // Fast lookup: state -> index
   hash_map< mimir::search::State, int > state_to_index_;

   // Ordered nodes for stable iteration
   std::vector< Node > nodes_ordered_;

   // Adjacency: parent_idx -> {child_idx, ...}
   hash_map< int, std::vector< int > > adjacency_;
};

}  // namespace mifrost
