#pragma once

#include <loki/details/utils/hash.hpp>
#include <mimir/formalism/ground_action.hpp>
#include <mimir/search/state.hpp>
#include <optional>
#include <vector>

#include "common_types.hpp"

// Delegate to mimir's existing loki::Hash<State> specialization
namespace std {
template <>
struct hash< mimir::search::State > {
   std::size_t operator()(const mimir::search::State& state) const noexcept
   {
      return loki::Hash< mimir::search::State >{}(state);
   }
};
}  // namespace std

namespace mifrost {

/**
 * @brief Directed Acyclic Graph (DAG) of state transitions for lookahead encoding.
 *
 * Represents a tree/DAG of successor states reachable from a root state,
 * typically generated by IW search or other lookahead algorithms.
 *
 * Each node has:
 * - state: The state at this node (lightweight handle)
 * - index: Insertion order (stable for iteration)
 * - depth: Distance from root
 * - action: Optional action that led to this state
 *
 * Edges represent parent→child transitions in the search tree.
 */
class TransitionDAG {
  public:
   /// One transition DAG node.
   struct Node {
      /// State represented by this node.
      mimir::search::State state;
      /// Stable insertion-order index.
      int64_t index;
      /// Depth from root.
      int depth;
      /// Optional incoming action from parent to this node.
      std::optional< mimir::formalism::GroundAction > action;
   };

   /**
    * @brief Construct a new TransitionDAG with the given root state.
    */
   explicit TransitionDAG(mimir::search::State root);

   /**
    * @brief Register a transition from parent to child.
    *
    * If the child state doesn't exist yet, it will be added.
    *
    * @param parent Parent state
    * @param child Child state
    * @param action Optional action that led from parent to child
    * @return Pair of (parent_idx, child_idx)
    */
   std::pair< int, int > register_transition(
      mimir::search::State parent,
      mimir::search::State child,
      std::optional< mimir::formalism::GroundAction > action = std::nullopt
   );

   /**
    * @brief Get the index of a state in the DAG.
    * @throws std::out_of_range if state not in DAG
    */
   int index(mimir::search::State state) const;

   /**
    * @brief Get the depth of a node by index.
    */
   int depth(int idx) const;

   /**
    * @brief Get the action that led to a node by index.
    */
   std::optional< mimir::formalism::GroundAction > action(int idx) const;

   /**
    * @brief Get the state at a given index.
    */
   mimir::search::State state(int idx) const;

   /**
    * @brief Get children indices of a node.
    */
   std::vector< int > children(int parent_idx) const;

   /**
    * @brief Get all nodes in insertion order.
    */
   const std::vector< Node >& nodes() const { return nodes_ordered_; }

   /**
    * @brief Get all successor nodes (excluding root).
    */
   std::vector< Node > successors() const;

   /**
    * @brief Get all transitions as (parent_idx, child_idx) pairs.
    */
   std::vector< std::pair< int, int > > transitions() const;

   /**
    * @brief Get the root state.
    */
   mimir::search::State root() const { return root_; }

   /**
    * @brief Get the root index (always 0).
    */
   int root_index() const { return 0; }

   /**
    * @brief Check if a state exists in the DAG.
    */
   bool contains(mimir::search::State state) const;

  private:
   /// Recompute depth labels from current adjacency.
   void finalize_depths();

   mimir::search::State root_;
   int next_index_ = 0;

   // Fast lookup: state -> index
   hash_map< mimir::search::State, int > state_to_index_;

   // Ordered nodes for stable iteration
   std::vector< Node > nodes_ordered_;

   // Adjacency: parent_idx -> {child_idx, ...}
   hash_map< int, std::vector< int > > adjacency_;
};

}  // namespace mifrost
