#pragma once

#include <concepts>
#include <loki/details/utils/hash.hpp>
#include <mimir/formalism/ground_action.hpp>
#include <mimir/search/state.hpp>
#include <optional>
#include <ranges>
#include <type_traits>
#include <vector>

#include "common_types.hpp"
#include "mifrost/core/utils/type_traits.hpp"

// Delegate to mimir's existing loki::Hash<State> specialization
namespace std {
template <>
struct hash< mimir::search::State > {
   std::size_t operator()(const mimir::search::State& state) const noexcept
   {
      return loki::Hash< mimir::search::State >{}(state);
   }
};
}  // namespace std

namespace mifrost {

/**
 * @brief Directed Acyclic Graph (DAG) of state transitions for lookahead encoding.
 *
 * Represents a tree/DAG of successor states reachable from a root state,
 * typically generated by IW search or other lookahead algorithms.
 *
 * Each node has:
 * - state: The state at this node (lightweight handle)
 * - index: Insertion order (stable for iteration)
 * - depth: Distance from root
 * - action: Optional action that led to this state
 *
 * Edges represent parent→child transitions in the search tree.
 */
class TransitionDAG {
  public:
   /// One bulk transition import record.
   struct TransitionRecord {
      mimir::search::State parent;
      mimir::search::State child;
      std::optional< mimir::formalism::GroundAction > action;
   };

   /// One transition DAG node.
   struct Node {
      /// State represented by this node.
      mimir::search::State state;
      /// Stable insertion-order index.
      int64_t index;
      /// Depth from root.
      int depth;
      /// Optional incoming action from parent to this node.
      std::optional< mimir::formalism::GroundAction > action;
   };

   /**
    * @brief Construct a new TransitionDAG with the given root state.
    */
   explicit TransitionDAG(mimir::search::State root);

   /**
    * @brief Register a transition from parent to child.
    *
    * If the child state doesn't exist yet, it will be added.
    *
    * @param parent Parent state
    * @param child Child state
    * @param action Optional action that led from parent to child
    * @return Pair of (parent_idx, child_idx)
    */
   std::pair< int, int > register_transition(
      const mimir::search::State& parent,
      const mimir::search::State& child,
      std::optional< mimir::formalism::GroundAction > action = std::nullopt
   );

   /**
    * @brief Register many transitions and recompute depths once.
    *
    * This accepts any input range of transition-like records exposing
    * ``parent``, ``child``, and ``action`` members.
    */
   template < std::ranges::input_range R >
      requires requires(detail::raw_t< std::ranges::range_reference_t< R > > rec) {
         { rec.parent } -> std::convertible_to< mimir::search::State >;
         { rec.child } -> std::convertible_to< mimir::search::State >;
         { rec.action } -> std::convertible_to< std::optional< mimir::formalism::GroundAction > >;
      }
   void register_transitions(R&& transitions)
   {
      bool has_records = false;
      for(auto&& rec : transitions) {
         has_records = true;
         register_transition_impl(rec.parent, rec.child, rec.action, false, false);
      }
      if(has_records) {
         finalize_depths();
      }
   }

   /**
    * @brief Get the index of a state in the DAG.
    * @throws std::out_of_range if state not in DAG
    */
   int index(const mimir::search::State& state) const;

   /**
    * @brief Get the depth of a node by index.
    */
   int depth(int idx) const;

   /**
    * @brief Get the action that led to a node by index.
    */
   std::optional< mimir::formalism::GroundAction > action(int idx) const;

   /**
    * @brief Get the state at a given index.
    */
   mimir::search::State state(int idx) const;

   /**
    * @brief Get children indices of a node.
    */
   const std::vector< int >* children(int parent_idx) const;

   /**
    * @brief Get all nodes in insertion order.
    */
   const std::vector< Node >& nodes() const { return nodes_ordered_; }

   /**
    * @brief Get all successor nodes (excluding root).
    */
   std::vector< Node > successors() const;

   /**
    * @brief Get all transitions as (parent_idx, child_idx) pairs.
    */
   std::vector< std::pair< int, int > > transitions() const;

   /**
    * @brief Get the root state.
    */
   mimir::search::State root() const { return root_; }

   /**
    * @brief Get the root index (always 0).
    */
   int root_index() const { return 0; }

   /**
    * @brief Check if a state exists in the DAG.
    */
   bool contains(const mimir::search::State& state) const;

  private:
   int get_or_add_node(
      const mimir::search::State& state,
      const std::optional< mimir::formalism::GroundAction >& action_for_new_node
   );

   std::pair< int, int > register_transition_impl(
      const mimir::search::State& parent,
      const mimir::search::State& child,
      const std::optional< mimir::formalism::GroundAction >& action,
      bool recompute_depths,
      bool require_parent_exists
   );

   /// Recompute depth labels from current adjacency.
   void finalize_depths();

   mimir::search::State root_;
   int next_index_ = 0;

   // Fast lookup: state -> index
   hash_map< mimir::search::State, int > state_to_index_;

   // Ordered nodes for stable iteration
   std::vector< Node > nodes_ordered_;

   // Adjacency: parent_idx -> {child_idx, ...}
   hash_map< int, std::vector< int > > adjacency_;
};

}  // namespace mifrost
