name: Install & Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "**"

env:
  MIFROST_MACOSX_DEPLOYMENT_TARGET: "11.0"

jobs:
  build:
    name: Install test (${{ matrix.os }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            python-version: "3.12"
            allow_failure: false
          - os: macos-latest
            python-version: "3.13"
            allow_failure: false
          - os: macos-latest
            python-version: "3.14"
            allow_failure: false
          - os: ubuntu-latest
            python-version: "3.12"
            allow_failure: false
          - os: ubuntu-latest
            python-version: "3.13"
            allow_failure: false
          - os: ubuntu-latest
            python-version: "3.14"
            allow_failure: false

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set Conan cache dir
      run: echo "CONAN_HOME=$GITHUB_WORKSPACE/.conan2" >> $GITHUB_ENV
      shell: bash

    - name: Restore Conan cache
      id: conan_cache_restore
      uses: actions/cache/restore@v5

      with:
        path: ${{ env.CONAN_HOME }}
        key: conan-${{ runner.os }}-${{ runner.arch }}-${{ runner.os == 'macOS' && env.MIFROST_MACOSX_DEPLOYMENT_TARGET || 'none' }}-${{ hashFiles('conanfile.py', 'conandata.yml', 'conan_export.py') }}
        restore-keys: |
          conan-${{ runner.os }}-${{ runner.arch }}-${{ runner.os == 'macOS' && env.MIFROST_MACOSX_DEPLOYMENT_TARGET || 'none' }}-
          conan-${{ runner.os }}-${{ runner.arch }}-

    - name: Set min macOS version
      if: runner.os == 'macOS'
      run: |
        echo "MACOSX_DEPLOYMENT_TARGET=${MIFROST_MACOSX_DEPLOYMENT_TARGET}" >> $GITHUB_ENV

    - name: Install test dependency
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/build.txt -r requirements/test.txt -r requirements.txt

    - name: Build and install
      id: build_install
      run: |
        python -m pip install -c requirements/constraints-ci.txt --no-build-isolation --verbose .

    - name: Test
      run: python -m pytest
